---
- name: Verify scenario with the default configuration
  hosts: all
  gather_facts: true
  become: no
  tasks:
    - name: Check splunk-otel-collector service
      ansible.windows.win_service:
        name: splunk-otel-collector
        state: started
      check_mode: yes
      register: service_status

    - name: Assert splunk-otel-collector service status
      assert:
        that: not service_status.changed

    - name: Check SPLUNK_CONFIG registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_CONFIG
        data: '{{ansible_env.ProgramData}}\Splunk\OpenTelemetry Collector\agent_config.yaml'
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SPLUNK_ACCESS_TOKEN registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_ACCESS_TOKEN
        data: fake-token
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SPLUNK_REALM registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_REALM
        data: fake-realm
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SPLUNK_API_URL registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_API_URL
        data: https://api.fake-realm.signalfx.com
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SPLUNK_HEC_TOKEN registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_HEC_TOKEN
        data: fake-token
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SPLUNK_HEC_URL registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_HEC_URL
        data: https://ingest.fake-realm.signalfx.com/v1/log
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SPLUNK_INGEST_URL registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_INGEST_URL
        data: https://ingest.fake-realm.signalfx.com
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SPLUNK_TRACE_URL registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SPLUNK_TRACE_URL
        data: https://ingest.fake-realm.signalfx.com/v2/trace
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check IIS registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\W3SVC
        state: present
        name: Environment
        data:
          - COR_ENABLE_PROFILING=true
          - COR_PROFILER={B4C89B0F-9908-4F73-9F59-0D77C5A06874}
          - CORECLR_ENABLE_PROFILING=true
          - CORECLR_PROFILER={B4C89B0F-9908-4F73-9F59-0D77C5A06874}
          - SIGNALFX_ENV=
          - SIGNALFX_PROFILER_ENABLED=false
          - SIGNALFX_PROFILER_MEMORY_ENABLED=false
          - SIGNALFX_SERVICE_NAME=
        type: multistring
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check SIGNALFX_DOTNET_TRACER_HOME registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: present
        name: SIGNALFX_DOTNET_TRACER_HOME
        data: C:\Program Files\SignalFx\.NET Tracing\
        type: string
      check_mode: yes
      register: reg_value

    - name: Assert registry value exists
      assert:
        that: not reg_value.changed

    - name: Check COR_ENABLE_PROFILING registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: COR_ENABLE_PROFILING
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed

    - name: Check COR_PROFILER registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: COR_PROFILER
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed

    - name: Check CORECLR_ENABLE_PROFILING registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: CORECLR_ENABLE_PROFILING
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed

    - name: Check CORECLR_PROFILER registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: CORECLR_PROFILER
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed

    - name: Check SIGNALFX_ENV registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: SIGNALFX_ENV
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed

    - name: Check SIGNALFX_SERVICE_NAME registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: SIGNALFX_SERVICE_NAME
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed

    - name: Check SIGNALFX_PROFILER_ENABLED registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: SIGNALFX_PROFILER_ENABLED
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed

    - name: Check SIGNALFX_PROFILER_MEMORY_ENABLED registry value
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
        state: absent
        name: SIGNALFX_PROFILER_MEMORY_ENABLED
      check_mode: yes
      register: reg_value

    - name: Assert registry value does not exist
      assert:
        that: not reg_value.changed
